version: "3.3"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: ../conf/mysql_env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

